### ISSUE TITLE
Failed to load the jekyll-new-post package

### ISSUE THREAD

**Issue by AshleyWright** [Arcath/jekyll-new-post#11]
[Enter steps to reproduce below:]
1. Restart Atom after update

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [jekyll-new-post](https://github.com/arcath/jekyll-new-post) package, v0.1.2
### Stack Trace

Failed to load the jekyll-new-post package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/ashleywright/.atom/packages/jekyll-new-post/lib/jekyll-new-post-view.coffee:1:1)
    at /Users/ashleywright/.atom/packages/jekyll-new-post/lib/jekyll-new-post-view.coffee:7:3
    at Object.<anonymous> (/Users/ashleywright/.atom/packages/jekyll-new-post/lib/jekyll-new-post-view.coffee:7:3)
    at Object.<anonymous> (/Users/ashleywright/.atom/packages/jekyll-new-post/lib/jekyll-new-post-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/ashleywright/.atom/packages/jekyll-new-post/lib/jekyll-new-post.coffee:1:21)
    at Object.<anonymous> (/Users/ashleywright/.atom/packages/jekyll-new-post/lib/jekyll-new-post.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "background-tips",
      "synesthesia",
      "font-viewer",
      "quick-editor",
      "svg-preview",
      "slack-chat",
      "symbols-view"
    ],
    "packagesWithKeymapsDisabled": [
      "bottom-dock",
      "punchclock",
      "tree-view",
      "term2",
      "symbols-tree-view",
      "tree-view-git-status",
      "git-blame",
      "git-control",
      "status-bar",
      "sublime-panes",
      "project-ring",
      "tree-ignore"
    ],
    "themes": [
      "one-dark-ui",
      "cobalt2-syntax"
    ],
    "destroyEmptyPanes": false
  }
}
```
### Installed Packages

``` coffee
# User
Rdio, v0.6.0
Stylus, v1.2.1
Sublime-Style-Column-Selection, v1.3.0
aligner, v0.17.1
aligner-php, v1.0.0
aligner-scss, v1.1.0
antialiased, v0.1.0
atom-image-resize, v0.3.0
autocomplete-ctags, v0.3.2
autocomplete-modules, v1.3.1
autocomplete-php, v0.3.7
blackspace, v1.1.0
bottom-dock, v0.3.5
change-case, v0.6.0
cobalt2-syntax, v0.2.1
coffee-navigator, v0.0.16
color-picker, v2.0.13
copy-to-hipchat, v0.1.0
css-comb, v2.4.0
ctags-status, v1.3.3
dash-on-cursor, v0.1.0
docblockr, v0.7.3
editorconfig, v1.2.0
emmet, v2.3.13
emmet-snippets-compatibility, v1.0.0
file-icons, v1.6.11
git-hide, v0.1.2
git-log, v0.4.1
grunt-manager, v0.1.11
gulp-manager, v0.2.13
gutter-shadow, v0.5.0
hex, v0.6.2
highlight-line, v0.11.0
highlight-selected, v0.10.1
http-status-codes, v1.0.4
imdone-atom, v1.1.49
jekyll-new-post, v0.1.2
jshint, v1.8.1
language-SCSS, v0.4.0
language-dots, v0.0.4
language-log, v1.1.0
language-lua, v0.9.4
language-pfm, v0.82.0
language-plantuml, v0.1.1
language-sql-mysql, v0.3.1
linter, v1.9.1
linter-coffeescript, v1.0.0
linter-jshint, v1.2.1
linter-less, v2.2.0
linter-manager, v0.2.4
linter-php, v1.0.5
linter-scss-lint, v2.4.0
linter-stylint, v2.0.1
linter-xmllint, v0.0.7
markdown-preview-opener, v0.1.1
minimap, v4.15.0
minimap-autohide, v0.10.1
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.1
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
multi-wrap-guide, v0.22.3
pdf-view, v0.34.0
pigments, v0.18.1
preview-inline, v0.5.1
project-colorize, v0.2.0
project-ring, v0.35.2
punchclock, v0.6.5
quick-docs, v0.1.0
simple-drag-drop-text, v0.3.0
smart-tags, v0.1.0
space-tab, v0.4.2
status-bar-clock, v2.0.4
symbols-tree-view, v0.10.1
tag, v0.3.0
todo-manager, v0.2.5
tree-ignore, v0.2.6
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by danielgomezrico** [comment]
Same for me.

**Comment by flaccid** [comment]
Me too.

**Comment by daimeonpilcher** [comment]
Same here.

**Comment by whaleen** [comment]
And myself.

**Comment by calebeby** [comment]
me too.
