### ISSUE TITLE
Failed to activate the jekyll-new-post package

### ISSUE THREAD

**Issue by shadowlightwolf89** [Arcath/jekyll-new-post#6]
[Enter steps to reproduce below:]
1. tried updating deprecations
2. restart and this...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [jekyll-new-post](https://github.com/arcath/jekyll-new-post) package, v0.1.2
### Stack Trace

Failed to activate the jekyll-new-post package

```
At 0 is not a valid selector in C:\Users\Rowan\.atom\packages\jekyll-new-post\package.json

SyntaxError: 0 is not a valid selector in C:\Users\Rowan\.atom\packages\jekyll-new-post\package.json
  at exports.validateSelector (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\clear-cut\index.js:115:19)
  at CommandRegistry.module.exports.CommandRegistry.add (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:47:9)
  at C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:753:70
  at Package.module.exports.Package.subscribeToActivationCommands (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:782:11)
  at C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:165:15)
  at Package.module.exports.Package.activate (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:452:21)
  at C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:436:29
  at Config.module.exports.Config.transact (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:431:19)
  at PackageManager.module.exports.PackageManager.activate (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:412:46)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\atom.js:641:21)
  at Object.<anonymous> (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Rowan\AppData\Local\atom\app-1.0.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/Rowan/AppData/Local/atom/app-1.0.0/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///C:/Users/Rowan/AppData/Local/atom/app-1.0.0/resources/app.asar/static/index.js:36:7)

  at C:\Users\Rowan\.atom\packages\jekyll-new-post\package.json:1:1
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "projectHome": "C:\\Users\\Rowan\\Projects",
    "disabledPackages": [
      "typewriter",
      "Zen",
      "minimap-autohide",
      "project-manager",
      "project-sidebar",
      "project-switcher2",
      "project-view",
      "highlight-selected",
      "minimap-highlight-selected",
      "jekyll",
      "cdnjs",
      "editorconfig",
      "atom-html-preview",
      "browser-plus",
      "colors",
      "minimap-find-and-replace",
      "minimap-bookmarks",
      "minimap-pigments",
      "minimap-selection"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-terminal-panel, v4.4.4
browser-refresh, v0.9.0
color-picker, v2.0.7
irc, v0.4.0
minimap, v4.10.0
minimap-git-diff, v4.1.3
new-file-plus, v0.2.1
pigments, v0.8.0
project-ring, v0.31.0
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by xunorus** [comment]
Same here, my log is:

Failed to activate the jekyll-new-post package
Cannot read property 'prototype' of undefined
Hide Stack Trace
TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/myfolder/.atom/packages/jekyll-new-post/lib/jekyll-new-post-view.coffee:1:1)
    at /home/myfolder/.atom/packages/jekyll-new-post/lib/jekyll-new-post-view.coffee:7:3
    at Object.<anonymous> (/home/myfolder/.atom/packages/jekyll-new-post/lib/jekyll-new-post-view.coffee:7:3)
    at Object.<anonymous> (/home/myfolder/.atom/packages/jekyll-new-post/lib/jekyll-new-post-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee](/opt/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
